name: Deploy to Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Execute deploy script on EC2
    - name: Execute deploy script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}  # GitHub Secrets에 저장된 SSH 비밀 키
        port: 22
        script: |
          cd ~/STUDIO-EYE-WEB-PROMOTION
          git pull origin main
          sudo systemctl restart nginx
