name: Deploy to ec2 server

on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.1' # 서버에서 사용 중인 Node.js 버전

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: CI=false npm run build

      - name: Execute deploy script on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd ~/STUDIO-EYE-WEB-PROMOTION
            git pull origin develop  
            npm install
            npm run build  
            sudo systemctl restart nginx
