name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        CI=false npm run build

    - name: Create private key file
      run: |
        echo "${{ secrets.SERVER_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Copy files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "build/*"
        target: "/home/ubuntu/STUDIO-EYE-WEB-PROMOTION/build"

    - name: List files in build directory
      run: ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} ls -la /home/ubuntu/STUDIO-EYE-WEB-PROMOTION/build

    - name: Check index.html content
      run: ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} cat /home/ubuntu/STUDIO-EYE-WEB-PROMOTION/build/index.html

    - name: Restart Nginx
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
        sudo systemctl restart nginx
        EOF
