name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies and build
      run: |
        npm install
        npm run build  # 빌드 과정에서 build 폴더 생성

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build  # 빌드된 파일을 업로드

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build  # build 작업이 완료된 후 실행

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3  # 업로드된 build 파일 다운로드
      with:
        name: build

    - name: Deploy to EC2 via SCP
      run: |
        scp -o StrictHostKeyChecking=no -r build/ ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/STUDIO-EYE-WEB-PROMOTION/build
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
